name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 17

    - name: Enable Coursier cache
      uses: coursier/cache-action@v6

    - name: Install Coursier & SBT
      uses: coursier/setup-action@v1

    - name: Build and Test
      run: sbt coverage test coverageReport

    - name: Save Coverage Report as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: target/scala-3.2.2/scoverage-report/

    - name: Upload Test Results to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/test-reports/

